apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiraz-cloud-com-tls
spec:
  secretName: kiraz-cloud-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kirazcloud.com
  dnsNames:
    - kirazcloud.com
    - www.kirazcloud.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kirazcloud.com
          - www.kirazcloud.com
